Repository Team18Contact/ContactApp, pull requests merged in 2023-09, with the labels that each got.

#1 [Feature] main-page
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/MainActivity.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/detail/DetailFragment.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/java/com/example/contactapp/main/MainTabs.kt
  app/src/main/java/com/example/contactapp/main/MainViewPagerAdapter.kt
  app/src/main/res/drawable/ic_add_contact.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#2 [Feature] login & Signup Page
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
  app/src/main/res/drawable/button_background2_rect.xml
  app/src/main/res/drawable/button_background_rect.xml
  app/src/main/res/drawable/daytask.png
  app/src/main/res/drawable/eyelash.png
  app/src/main/res/drawable/lock.png
  app/src/main/res/drawable/logo1.png
  app/src/main/res/drawable/logo2.png
  app/src/main/res/drawable/logo3.png
  app/src/main/res/drawable/logo4.png
  app/src/main/res/drawable/logo5.png
  app/src/main/res/drawable/usertag.png
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#3 [UI] Feature/detail
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/drawable/detail_email.png
  app/src/main/res/drawable/detail_name.png
  app/src/main/res/drawable/detail_phone.png
  app/src/main/res/layout/fragment_detail.xml
Labels: UI

#4 Feature ContactListFragment 구현
  app/build.gradle
  app/src/main/java/com/example/contactapp/contact/Constants.kt
  app/src/main/java/com/example/contactapp/contact/ContactAdapter.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactModel.kt
  app/src/main/res/drawable/ic_dots.png
  app/src/main/res/drawable/ic_empty_heart.xml
  app/src/main/res/drawable/ic_heart.png
  app/src/main/res/drawable/img_frank.png
  app/src/main/res/drawable/img_hsh.png
  app/src/main/res/drawable/img_jgd.png
  app/src/main/res/drawable/img_jjw.png
  app/src/main/res/drawable/img_jsj.png
  app/src/main/res/drawable/img_jys.png
  app/src/main/res/drawable/img_kds.png
  app/src/main/res/drawable/img_ljm.png
  app/src/main/res/drawable/img_lmh.png
  app/src/main/res/layout/contact_item.xml
  app/src/main/res/layout/fragment_contact_list.xml
Labels: feature

#5 [FEAT] Feature/detail
  .idea/misc.xml
  app/src/main/java/com/example/contactapp/contact/ContactAdapter.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactModel.kt
  app/src/main/java/com/example/contactapp/detail/DetailFragment.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feature

#6 로그인/회원가입 페이지 완성
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
Labels: feature

#7 로그인/회원가입 페이지 완성
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
  app/src/main/res/drawable/button_background2_rect.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feature

#9 [FEATURE/UI] GridView / ListView Type 변경
  .gitignore
  .idea/misc.xml
  app/src/main/java/com/example/contactapp/contact/ContactAdapter.kt
  app/src/main/java/com/example/contactapp/contact/ContactGridViewAdapter.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactModel.kt
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/java/com/example/contactapp/main/MainViewPagerAdapter.kt
  app/src/main/res/drawable/border_item.xml
  app/src/main/res/drawable/ic_grid_view.xml
  app/src/main/res/drawable/ic_list_view.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_gridview_item.xml
  app/src/main/res/layout/contact_item.xml
  app/src/main/res/layout/contact_recyclerview_item.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#10 [FEATURE] Activity - Fragment 데이터 전달 코드
  app/src/main/java/com/example/contactapp/detail/DetailFragment.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
Labels: feature

#11 Feature/login
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feature

#12 [FEATURE] RecyclerView LTR/RTL 변경
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
Labels: feature

#13 [FEATURE] 실제 연락처 불러오기 & Swipe 기능 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactListItemHelper.kt
  app/src/main/java/com/example/contactapp/contact/ContactModel.kt
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
  app/src/main/res/drawable/border_item_background_black.xml
  app/src/main/res/drawable/border_item_background_yellow.xml
  app/src/main/res/drawable/ic_call.xml
  app/src/main/res/drawable/ic_empty_user.png
  app/src/main/res/layout/contact_gridview_item.xml
  app/src/main/res/layout/contact_recyclerview_item.xml
Labels: feature

#14 [FEAT] Feature/mypage
  app/src/main/java/com/example/contactapp/detail/DetailFragment.kt
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/java/com/example/contactapp/signUp/SignUpActivity.kt
  app/src/main/res/drawable/login_moving_logo.png
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#15 [FEATURE] GridView 수정
  app/src/main/java/com/example/contactapp/contact/ContactGridViewAdapter.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactListItemHelper.kt
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/res/layout/fragment_contact_list.xml
Labels: feature

#16 [FEATURE] 연락처 추가 & Notification & 좋아요 목록 상단 출력 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contactapp/contact/Constants.kt
  app/src/main/java/com/example/contactapp/contact/ContactListFragment.kt
  app/src/main/java/com/example/contactapp/contact/ContactModel.kt
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/java/com/example/contactapp/detail/DetailFragment.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/res/color/pressed_chip.xml
  app/src/main/res/drawable/dialog_edt_rectangle.xml
  app/src/main/res/drawable/ic_add_profile.png
  app/src/main/res/drawable/ic_empty_user.png
  app/src/main/res/drawable/ic_full_heart.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/contact_recyclerview_item.xml
  app/src/main/res/layout/dialog_add_contact.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#17 [Refactoring]
  app/src/main/java/com/example/contactapp/contact/ContactRecyclerViewAdapter.kt
  app/src/main/java/com/example/contactapp/main/MainActivity.kt
  app/src/main/java/com/example/contactapp/signIn/SignInActivity.kt
  app/src/main/res/layout/contact_gridview_item.xml
  app/src/main/res/layout/contact_recyclerview_item.xml
  app/src/main/res/layout/dialog_add_contact.xml
  app/src/main/res/layout/fragment_detail.xml
Labels: feature
